services:
  orion:
    extends:
      file: docker-compose-common.yml
      service: orion
    depends_on:
      - mongo

  quantumleap:
    extends:
      file: docker-compose-common.yml
      service: quantumleap
    depends_on:
      - crate
      - redis
      - orion

  mongo:
    extends:
      file: docker-compose-common.yml
      service: mongo

  crate:
    extends:
      file: docker-compose-common.yml
      service: crate

  timescale:
    extends:
      file: docker-compose-common.yml
      service: timescale

  grafana:
    extends:
      file: docker-compose-common.yml
      service: grafana
    depends_on:
      - crate

  redis:
    extends:
      file: docker-compose-common.yml
      service: redis

  homeassistant:
    extends:
      file: docker-compose-common.yml
      service: homeassistant

volumes:
  mongodata:
  cratedata:
  redisdata:

networks:
  demo:
    name: demo
    driver: bridge