services:
  orion:
    image: fiware/orion-ld:1.4.0
    ports:
      - "1026:1026"
    command: -logLevel DEBUG -dbhost mongo
    depends_on:
      - mongo
    networks:
      - demo

  mongo:
    image: mongo:${MONGO_VERSION:-4.4}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - demo

  crate:
    image: crate:${CRATE_VERSION:-4.6.7}
    command: >
      crate
      -Cauth.host_based.enabled=false
      -Ccluster.name=democluster
      -Chttp.cors.enabled=true
      -Chttp.cors.allow-origin="*"
      -Cpsql.enabled=true
      -Cpsql.port=5432
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    ports:
      - "4200:4200"
      - "4300:4300"
    expose:
      - "5432"
    volumes:
      - cratedata:/data
    networks:
      - demo

  redis:
    image: redis:${REDIS_VERSION:-6.2.3}
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - demo

  timescale:
    image: timescale/timescaledb-ha:${TIMESCALE_VERSION:-pg13.16-ts2.15.3-oss}
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
    networks:
      - demo

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    networks:
      - demo

  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - C:/Users/herod/Desktop/DEMI/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8123:8123"
    networks:
      - demo
  quantumleap:
    image: orchestracities/quantumleap:${QL_VERSION:-latest}
    ports:
      - "8668:8668"
    environment:
      QL_TABLE_PREFIX: "mt_"
      QL_USE_GEOCODING: "false"

      # --- NGSI-LD mode ---
      QL_ENABLE_NGSI_LD: "true"

      # ---- DB target (CrateDB) ----
      QL_DEFAULT_DB: "crate"
      CRATE_HOST: "crate"
      CRATE_PORT: "4200"

      # ---- Logging ----
      LOGLEVEL: "DEBUG"
    depends_on:
      - crate
      - redis
    networks:
      - demo